# Generated by Django 5.0.6 on 2024-06-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_survey_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
