# Generated by Django 5.0.6 on 2024-06-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_survey_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
